### ISSUE TITLE
v1.3.9 erroring

### ISSUE THREAD

**Issue by benedfit** [rossPatton/stylint#296]
As of `v1.3.9` styling errors with the following message:

```
/usr/local/lib/node_modules/stylint/src/utils/getFiles.js:25
				excluded = excluded || exclude.match( relPath )
				                               ^
TypeError: Object #<Glob> has no method 'match'
    at /usr/local/lib/node_modules/stylint/src/utils/getFiles.js:25:36
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/stylint/src/utils/getFiles.js:24:24)
    at Array.filter (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/stylint/src/utils/getFiles.js:20:17)
    at f (/usr/local/lib/node_modules/stylint/node_modules/glob/node_modules/once/once.js:17:25)
    at Glob.<anonymous> (/usr/local/lib/node_modules/stylint/node_modules/glob/glob.js:146:7)
    at Glob.emit (events.js:95:17)
    at Glob._finish (/usr/local/lib/node_modules/stylint/node_modules/glob/glob.js:194:8)
    at done (/usr/local/lib/node_modules/stylint/node_modules/glob/glob.js:179:14)
```

**Comment by SimenB** [comment]
@wojciechczerniak

**Comment by ucarion** [comment]
I'm getting a similar error on `1.3.10`:

```
/opt/boxen/nodenv/versions/v4.2.1/lib/node_modules/stylint/src/utils/getFiles.js:25
				excluded = excluded || exclude.match( relPath )
				                               ^

TypeError: exclude.match is not a function
    at /opt/boxen/nodenv/versions/v4.2.1/lib/node_modules/stylint/src/utils/getFiles.js:25:36
    at Array.forEach (native)
    at Object.<anonymous> (/opt/boxen/nodenv/versions/v4.2.1/lib/node_modules/stylint/src/utils/getFiles.js:24:24)
    at Array.filter (native)
    at Object.<anonymous> (/opt/boxen/nodenv/versions/v4.2.1/lib/node_modules/stylint/src/utils/getFiles.js:20:17)
    at f (/opt/boxen/nodenv/versions/v4.2.1/lib/node_modules/stylint/node_modules/glob/node_modules/once/once.js:17:25)
    at Glob.<anonymous> (/opt/boxen/nodenv/versions/v4.2.1/lib/node_modules/stylint/node_modules/glob/glob.js:146:7)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (/opt/boxen/nodenv/versions/v4.2.1/lib/node_modules/stylint/node_modules/glob/glob.js:194:8)
```

**Comment by SimenB** [comment]
@wojciechczerniak @rossPatton 
Is this a change that should be reverted?

**Comment by SimenB** [comment]
This is #272

**Comment by wojciechczerniak** [comment]
@SimenB since it says `Object #<Glob> has no method 'match'` I guess it's related to commit [Don't depend on minimatch](https://github.com/rossPatton/stylint/commit/1c3b60a3641a2069f283846937325b27036c46ad) because we map all patterns to different object now. `match` is a method in [minimatch](https://github.com/isaacs/minimatch) and probably does not exist in `glob`.

We need to update `getFiles.js:25` how pattern is checked by [glob](https://github.com/isaacs/node-glob)?

**Comment by SimenB** [comment]
Glob is minimatch under the hood.

A random quote from glob's readme also suggests that should work.

> For example, glob.match([], "\\*a\\?") will return "\\*a\\?" rather than "*a?".

**Comment by wojciechczerniak** [comment]
Glob object is created but without the `match` method to call. Maybe a case when wrong pattern is configured?

**Comment by SimenB** [comment]
Hmm, yeah.

@benedfit @ucarion could you post your `.stylintrc`?

**Comment by benedfit** [comment]
```json
{
  "exclude": [ "node_modules/**/*.styl" ],
  "blocks": {
    "expect": "never",
    "error": true
  },
  "brackets": {
    "expect": "never",
    "error": true
  },
  "colons": {
    "expect": "never",
    "error": true
  },
  "colors": {
    "expect": "always",
    "error": true
  },
  "commaSpace": {
    "expect": "always",
    "error": true
  },
  "commentSpace": {
    "expect": false,
    "error": true
  },
  "cssLiteral": {
    "expect": "never",
    "error": true
  },
  "depthLimit": {
    "expect": false,
    "error": true
  },
  "duplicates": {
    "expect": true,
    "error": true
  },
  "efficient": {
    "expect": "always",
    "error": true
  },
  "extendPref": {
    "expect": "@extend",
    "error": true
  },
  "globalDupe": false,
  "indentPref": {
    "expect": 2,
    "error": true
  },
  "leadingZero": {
    "expect": "always",
    "error": true
  },
  "maxErrors": false,
  "maxWarnings": false,
  "mixed": {
    "expect": true,
    "error": true
  },
  "namingConvention": {
    "expect": "BEM",
    "error": true
  },
  "namingConventionStrict": {
    "expect": true,
    "error": true
  },
  "none": {
    "expect": "never",
    "error": true
  },
  "noImportant": {
    "expect": true,
    "error": true
  },
  "parenSpace": {
    "expect": "never",
    "error": true
  },
  "placeholders": {
    "expect": "always",
    "error": true
  },
  "prefixVarsWithDollar": {
    "expect": "always",
    "error": true
  },
  "quotePref": {
    "expect": "single",
    "error": true
  },
  "semicolons": {
    "expect": "never",
    "error": true
  },
  "sortOrder": {
    "expect": false,
    "error": true
  },
  "stackedProperties": {
    "expect": "never",
    "error": true
  },
  "trailingWhitespace": {
    "expect": "never",
    "error": true
  },
  "universal": {
    "expect": true,
    "error": true
  },
  "valid": {
    "expect": true,
    "error": true
  },
  "zeroUnits": {
    "expect": "never",
    "error": true
  },
  "zIndexNormalize": {
    "expect": false,
    "error": true
  }
}
```

I guess it's falling down on the exclude patterns

**Comment by SimenB** [comment]
That seems perfectly valid. 

I'm not on a computer now, but I'll take a look later today. 

I can't see if we have any tests for `exclude` (opening the test file actually crashes chrome on my phone...), seems like it should have caught this

**Comment by SimenB** [comment]
@wojciechczerniak You're right, calling returning the minimatch instance from the glob works. Nice find! Opened #322, but should add some tests...
