### ISSUE TITLE
v0.9.3 crashing

### ISSUE THREAD

**Issue by uglow** [rossPatton/stylint#86]
Hi Ross, 

I'm getting this stacktrace after upgrading to v0.9.3:

```console
>> 
>> /mydev/code/nab/ib-web/node_modules/stylint/src/checks/duplicates.js:62
>> 			if ( this.rootCache.indexOf( line ) !== -1 &&
>> 			                    ^
>> TypeError: Cannot call method 'indexOf' of undefined
>>     at Object.duplicateSelectors [as duplicates] (/mydev/code/nab/ib-web/node_modules/stylint/src/checks/duplicates.js:62:24)
>>     at Object.test (/mydev/code/nab/ib-web/node_modules/stylint/src/test.js:120:14)
>>     at /mydev/code/nab/ib-web/node_modules/stylint/src/parse.js:50:15
>>     at Array.forEach (native)
>>     at /mydev/code/nab/ib-web/node_modules/stylint/src/parse.js:46:9
>>     at fs.js:272:14
>>     at /mydev/code/nab/ib-web/node_modules/stylint/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:104:5
>>     at Object.oncomplete (fs.js:108:15)
>> Exited with code: 8.
```

My lint config:
```json
{
  "alphabetical": false,
  "borderNone": true,
  "brackets": false,
  "colons": false,
  "colors": false,
  "commaSpace": true,
  "commentSpace": false,
  "cssLiteral": false,
  "depthLimit": 3,
  "duplicates": true,
  "efficient": true,
  "enforceBlockStyle": false,
  "enforceVarStyle": true,
  "extendPref": "@extend",
  "globalDupe": true,
  "indentSpaces": 2,
  "leadingZero": false,
  "maxWarnings": 50,
  "maxWarningsKill": false,
  "mixed": true,
  "namingConvention": "BEM",
  "parenSpace": false,
  "placeholders": false,
  "semicolons": false,
  "universal": true,
  "valid": true,
  "whitespace": true,
  "zeroUnits": true,
  "zIndexDuplicates": false,
  "zIndexNormalize": false
}
```

It happens before I get any of the usual 43 BEM-naming errors that I was getting on v0.9.2.

**Comment by uglow** [comment]
On OSX latest (Yosemite?). Running task thru a gruntJS shell (grunt-exec plugin).

**Comment by rossPatton** [comment]
thanks, might get a chance to look tonight.

**Comment by rossPatton** [comment]
it might also help if you can include some of the stylus you were linting? 

if you disable the duplicates check do you still get the error?

**Comment by uglow** [comment]
If I set `"duplicates": false`, it works! But I get 30 errors (less than I was expecting, and none of them are the previous BEM naming errors):

```console
Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/fonts.styl
Line: 10: url($icon-font-path + 'corpidc1s-heavy-webfont.woff') format('woff'), 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/fonts.styl
Line: 11: url($icon-font-path + 'corpidc1s-heavy-webfont.ttf') format('truetype'), 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/fonts.styl
Line: 12: url($icon-font-path + 'corpidc1s-heavy-webfont.svg#CorpidC1sHeavyRegular') format('svg') 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/fonts.styl
Line: 27: url($icon-font-path + 'corpidc1s-light-webfont.woff') format('woff'), 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/fonts.styl
Line: 28: url($icon-font-path + 'corpidc1s-light-webfont.ttf') format('truetype'), 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/fonts.styl
Line: 29: url($icon-font-path + 'corpidc1s-light-webfont.svg#CorpidC1sLightRegular') format('svg') 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 16: padding: $padding-alpha $padding-delta 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 19: display: block 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 20: text-decoration: none 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 21: font-family: $font-family-brand-regular 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 22: color: $white 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 24: @media (max-width $screen-xs-max) 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 25: rem(11) 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 27: &:hover, &:focus 

Warning:  selector depth greater than 

Warning:  3:
File: src/modules/core/styles/component/footer.styl
Line: 28: text-decoration: underline 


30 Warnings
>> Exited with code: 1.
```

Sample of file that was giving BEM errors before:
```CSS
.pageContent {
  padding: 1em 1em;
}
/*h1 {*/
  /*margin: 0 0;*/
  /*font-weight: normal;*/
  /*color: #4D4D4D;*/
  /*padding: 0 0 .5em 0;*/
/*}*/
.bankTitle {
  font-weight: bold;
  padding-right: 2em;
}
.createNewGroup {
  float: right;
  margin-top: -2em;
  margin-right: 1em;
}
.accountList {
  background-color: #E3E5E6;
  padding: .5em .5em;
  max-width: 50em;
}
.groupTitle {
  font-size: 1.25em;
  padding-bottom: .25em;
  font-weight: bold;
}
.accountItem {
  background-color: #f4f5f7;
  padding: .5em .5em;
  min-height: 4.5em;
  margin-bottom: .3em;
  margin-left: 0;
  margin-right: 0;
}
.accountIcon,
.accountDetails {
  float: left;
}
.accountBalances {
  float: right;
  padding-right: .5em;
  text-align: right;
}
.accountIcon {
  height: 1.5em;
  background-color: #c20000;
  border-radius: 3em;
  width: 1.5em;
  margin-right: 1em;
  margin-top: .25em;
  text-align: center;
  line-height: 1.5em;
  color: #fff;
  font-size: 2em;
}
.accountDetails {
  padding: .25em 0;
  max-width: 45%;
}
.bsbAndNumber {
  font-weight: bold;
}
.accountBsb,
.accountNumber {
  display: inline-block;
}
.currentBalance {
  font-size: 1.75em;
  color: green;
}
.availableBalance {
  font-size: .8em;
}
.negativeBalance {
  color: #c20000;
}
.accountName {
  font-weight: bold;
  font-size: 1.25em;
}
.totalCreditBalance,
.totalDebitBalance,
.netPosition {
  text-align: right;
  padding: .5em .5em;
}
.totalBalance {
  font-size: 1.5em;
  padding-left: .5em;
}
.netPosition {
  font-weight: bold;
}
/* MOBILE STYLING */
@media (max-width: 640px), screen and (max-device-width: 480px) {
  .groupTitle {
    padding-left: .5em;
  }
  /*h1 {*/
    /*padding-left: .5em;*/
  /*}*/
  .accountList {
    width: 100%;
    max-width: 100%;
    padding: .5em 0;
  }
  .pageContent {
    padding: 1em 0;
  }
  .accountItem {
    padding: .5em 0;
  }
  .accountIcon {
    margin-left: .5em;
    margin-right: .5em;
  }
  .currentBalance {
    font-size: 1.5em;
  }
  .availableBalance {
    font-size: .8em;
  }
  .bsbAndNumber {
    font-size: .8em;
  }
}
```

**Comment by rossPatton** [comment]
hey @uglow if you get the latest version of stylint the duplicates issue should be fixed. That was an error on my part.

The other issue, the missing BEM errors, is actually a config change.

See: https://github.com/rossPatton/stylint/issues/44

Basically, if you set `namingConventionStrict: true` you'll get the old namingConvention setting back and you should see your 25 errors.

**Comment by uglow** [comment]
Thanks @rossPatton :)
